name: nd-server release

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "![0-9]+.[0-9]+.[0-9]+-dev[0-9]+"

permissions:
  contents: write
  id-token: write

jobs:
  release-ndserver:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        id: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
            virtualenvs-create: true
            virtualenvs-in-project: true
            installer-parallel: true
      - name: poetry build
        run: poetry build
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
      - name: pypi
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
